[package]
name = "dandelion"
version = "0.2.0"
authors = ["Antoine \"Anthony\" Sébert <antoine.sb@orange.fr>"]
edition = "2018"
publish = false
description = "Microkernel Real-Time Operating System in Rust"
homepage = "https://github.com/AntoineSebert/dandelion"
repository = "https://github.com/AntoineSebert/dandelion"
readme = "README.md"
keywords = ["real-time", "OS", "RTOS", "microkernel"]
categories = ["embedded", "no-std"]
license = "CC-BY-NC-SA-4.0"
maintenance = { status = "experimental" }

[[test]]
name = "panic_handler"
harness = false

[[test]]
name = "stack_overflow"
harness = false

#[doc]
#https://doc.rust-lang.org/rustdoc

[package.metadata.bootimage]
run-args = [
	"-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
	"-serial", "mon:stdio"
]
test-args = [
	"-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
	"-serial", "stdio",
	"-display", "none"
]
test-success-exit-code = 33
default-target = "x86_64-dandelion.json"

[dependencies]
array-init = "^0.0"
bitflags = "^1.0"
integer-sqrt = "^0.1"
pc-keyboard = "^0.5"
pic8259_simple = "^0.1"
spin = "^0.5"
uart_16550 = "^0.2"
volatile = "^0.2"
x86_64 = "^0.7"

[dependencies.arraydeque]
version = "^0.4"
default-features = false

[dependencies.bootloader]
version = "^0.6"
features = ["map_physical_memory"]

[dependencies.cmos]
version = "^0.1"
git = "https://github.com/AntoineSebert/cmos"

[dependencies.either]
version = "^1.5"
default-features = false

[dependencies.lazy_static]
version = "^1.3"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "^0.2"
default-features = false

[dev-dependencies]
array-init = "^0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
