[package]
name = "dandelion"
version = "0.2.0"
authors = ["Antoine \"Anthony\" Sébert <antoine.sb@orange.fr>"]
edition = "2018"
publish = false
description = "Microkernel Real-Time Operating System in Rust"
homepage = "https://github.com/AntoineSebert/dandelion"
repository = "https://github.com/AntoineSebert/dandelion"
readme = "README.md"
keywords = ["real-time", "OS", "RTOS", "microkernel"]
categories = ["embedded", "no-std"]
license = "CC-BY-NC-SA-4.0"
maintenance = { status = "experimental" }

#[doc]
#https://doc.rust-lang.org/rustdoc

[dependencies]
bootloader = { version = "^0.6", features = ["map_physical_memory"] }
volatile = "^0.2"
uart_16550 = "^0.2"
x86_64 = "^0.6"
pic8259_simple = "^0.1"
integer-sqrt = "^0.1"
cmos = { version = "^0.1", git = "https://github.com/AntoineSebert/cmos" }
array-init = "^0.0"
pc-keyboard = "^0.5"
spin = "^0.5"
arraydeque = { version = "^0.4", default-features = false }
either = { version = "^1.5", default-features = false }

[dependencies.num-traits]
version = "^0.2"
default-features = false

[dependencies.lazy_static]
version = "^1.3"
features = ["spin_no_std"]

[dev-dependencies]
array-init = "^0.0"

[package.metadata.bootimage]
default-target = "x86_64-dandelion.json"